### ISSUE TITLE
Layering saved line under/over green lines

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#121]
For https://github.com/phetsims/QA/issues/277 and https://github.com/phetsims/QA/issues/278
The green line appears to layer over the saved lines, but the pointer tool sticks to the saved lines over the green lines when they overlap.  Not sure which is intended to be out front.
![layersone](https://user-images.githubusercontent.com/41024075/52580103-e50ae280-2de4-11e9-892d-3aacfe23a91d.jpg)
![layerstwo](https://user-images.githubusercontent.com/41024075/52580104-e50ae280-2de4-11e9-8a30-ce611892a2de.jpg)

**Comment by pixelzoom** [comment]
This seems similar to https://github.com/phetsims/graphing-lines/issues/89, but involves a saved line and a "standard" line (y=x, y=-x).

**Comment by amanda-phet** [comment]
@pixelzoom thanks for finding that issue- I was looking for it! If we can prioritize the active/black line, then green line, then gray/saved line, I think that makes the most sense.

**Comment by pixelzoom** [comment]
The problem was that the model and view were using different orders for the lines.  Fixed in the above commits.  The order in model and view is now interactive line, standard lines, saved lines.

@KatieWoe please test in master.  Here's a quick test procedure that covers all of the cases:

1. Start Graphing Lines.
2. Go to Slope-Intercept screen.
3. Change interactive equation to y = 4/4 + 0
4. Press "Save line"
5. Check the "y=x" check box.
6. Put a point tool at (2,2).  It's display should be black (interactive line)
7. Change interactive equation to y = 5/4 + 0.  The point tool's display should change to green (y=x).
8. Uncheck the "y=x" check box. The point tool's display should change to gray (saved line).

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by pixelzoom** [comment]
Pending regression testing in the next RC.

**Comment by KatieWoe** [comment]
Looks good on both rcs.
