### ISSUE TITLE
Very slight pointer area overlap with number pickers

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#124]
For https://github.com/phetsims/QA/issues/286 and https://github.com/phetsims/QA/issues/287
There may be a bit of overlap in the down pointer area of of the numerator and the up arrow of the the denominator.  It hasn't caused any problems, and I'm not concerned about it.  Documenting Here.
![maybeoverlap](https://user-images.githubusercontent.com/41024075/52733052-f8ea4c00-2f7e-11e9-8aa7-f85b07ba8d7c.jpg)

**Comment by pixelzoom** [comment]
The problem was that the sim was using the mouseArea defaults for NumberPicker, and those need to be tweaked to support the numerator-over-denominator case.  So I've specified custom NumberPicker pointer areas in the above commits.  These values apply to all NumberPickers in the sim:

```js
// GLConstants.js
PICKER_OPTIONS: {
  touchAreaXDilation: 26,
  touchAreaYDilation: 4,
  mouseAreaXDilation: 0,
  mouseAreaYDilation: 4
}
```

Here's how they look for the 3 equation forms:

<img width="335" alt="screenshot_1060" src="https://user-images.githubusercontent.com/3046552/52818902-2ad5de00-3065-11e9-9d1f-b8a9f4b736a0.png">
<img width="248" alt="screenshot_1061" src="https://user-images.githubusercontent.com/3046552/52818910-2dd0ce80-3065-11e9-8f6d-c1fc7d48ab35.png">
<img width="365" alt="screenshot_1062" src="https://user-images.githubusercontent.com/3046552/52818915-30332880-3065-11e9-948b-2503de4031c0.png">

First we'll get @amanda-phet's approval.  Then we'll have @KatieWoe verify in master.

**Comment by amanda-phet** [comment]
Looks like a good solution to me. Thanks @KatieWoe and @pixelzoom !

**Comment by KatieWoe** [comment]
Confirmed on master

**Comment by pixelzoom** [comment]
Pending regression testing in 1.3.0-rc.4.

**Comment by KatieWoe** [comment]
Looks good in both rc-4's
