### ISSUE TITLE
Impossible challenge

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#127]
For https://github.com/phetsims/QA/issues/286#event-2135417335
On Level 3 of graphing lines the problem was given to use two points to make the line: y - 4 = 7/3 (x + 10).  However, only one point on this line falls in the 20x20 grid, meaning the correct line is impossible to create.
![28a7e07c-7929-44cd-9bf9-99bc128412f0](https://user-images.githubusercontent.com/41024075/52814305-0bd14f00-3059-11e9-9543-fdeba89656ab.png)

**Comment by KatieWoe** [comment]
Note that this seems very rare as I don't believe I have seen this during any of the testing before.

**Comment by pixelzoom** [comment]
Slack:

Kathryn Woessner [1:29 PM]
Don't know if https://github.com/phetsims/graphing-lines/issues/127 could show up in GSI as well.  Probably, but I haven't seen it.

Chris Malley [1:32 PM]
GSI has an entirely different challenge generation engine.
#127 also shows a point-slope form equation, while GSI is limited to slope-intercept form.

Kathryn Woessner [1:49 PM]
Yeah.  The only thing I can think of is if it asks to make a line with three points and only two are on the screen, but I don't know if that would happen

**Comment by pixelzoom** [comment]
This is a `GraphTheLine` challenge with `EquationForm.POINT_SLOPE`.  Level 3 will have either 1 or 2 of these challenges. See `ChallengeFactory3` lines 64 and 88.

**Comment by pixelzoom** [comment]
There was indeed a bug in `ChallengeFactory3`, the challenge generator for level 3.  It's probably been present since the Java version.  This is going to be a little complicated to explain, but here goes...

If you run with `?shuffle=false&showAnswers`, challenges will be presented in the order that matches the design doc, and labeled in the upper left corner.  The challenge that we're interested in is the 3rd challenge generated, which we'll refer to as challenge3.  The line form for challenge3 is randomly chosen for either slope-intercept or point-slope form.  The bug was present when challenge3 was using point-slope form.   The screen would look like this, with "3. GraphTheLine, point and slope variable" in the upper-left:

![screenshot_1063](https://user-images.githubusercontent.com/3046552/52821144-2a404600-306b-11e9-8d53-bf34a04af92a.jpg)

For challenge3, we should have been getting the slope from the "optional" pool or slope values, then  computing a point that works for that slope.  But we were failing to compute the point, and instead using the point from challenge2 (the second challenge generated). 

So... If you run 1.3.0-rc3 with `?shuffle=false&showAnswers`, and challenge3 is in point-slope form, then you'll see that it's using the same point as was used in challenge2.

If that's not totally clear, don't worry about it.  It's fixed in the above commits. 

Steps to verify:

1. Run from master with `?shuffle=false&showAnswers`
2. Go to Level 3.
3. Skip to the 2nd challenge.  
4. Note the point used for the 2nd challenge.
5. Skip to the 3rd challenge.  
6. If the 3rd challenge is in point-slope form, continue.  Otherwise press the Start Over button and go back to step 2.
7. Note the point for the 3rd challenge. 
8. Verify that the points for 2nd and 3rd challenges are not the same.

**Comment by KatieWoe** [comment]
They are different points

**Comment by pixelzoom** [comment]
Pending regression testing in 1.3.0-rc.4.

**Comment by KatieWoe** [comment]
1.3.0-rc.4 challenge 2 and 3 use different points.
