### ISSUE TITLE
Drag Listeners aren't interrupted

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-lines#156]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.4.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1066 (and https://github.com/phetsims/qa/issues/1067) on the first 3 screens when I am holding a sphere with one finger and press Reset All or use the number picker with another, the drag listener isn't interrupted. I see the same thing with the Point Tool and Reset All button. 

**Steps to reproduce**
Here is an example:
1. On the Slope Screen, move the purple sphere and hold it with one finger
2. Press Reset All with another finger
3. While still holding the sphere, change a value for it with the number picker 
4. Grab a Point tool and place it somewhere
5. While your finger is still on the Point tool, press Reset All with another finger

**Visuals**

https://github.com/phetsims/graphing-lines/assets/87318828/bfea3a3c-28e0-495c-bf41-18e0447e32c7

**Comment by pixelzoom** [comment]
This is an older sim, and was missing the call to `interruptSubtreeInput` that we've been adding to `resetAllButton`.  I've added them in the above commit.  Sure would be nice if we didn't need to add this manually to every sim, but I don't see an easy way to make that happen.

@Nancy-Salpepi please review in master. If it looks OK, assign back to me for cherry picking.

**Comment by Nancy-Salpepi** [comment]
@ pixelzoom 
-  When pressing Reset All, in addition to that sound I also hear the release sound for the sphere.
- It would also be good to interrupt the drag listener for the sphere when using the number picker.

**Comment by pixelzoom** [comment]
> When pressing Reset All, in addition to that sound I also hear the release sound for the sphere.

The grab/release sounds are handled by RichDragListener, and the sim does not have any control over muting its sounds. So I suspect that other sims using RichDragListener (area-model suite, FEL, KL, MSAB, wave-interfernce) also have this problem.   There's probably something that  RichDragListener should be checking before playing the release sound, to verify that it has not been released due to an interruption. @AgustinVallejo @zepumph FYI, since you've been working on RichDragListener/RichKeyboardDragListener.

> It would also be good to interrupt the drag listener for the sphere when using the number picker.

And visa versa, I suspect.  In this case, it's complicated to be that selective about what to interrupt -- the manipulators and NumberPickers are in entirely different areas of the code.   I don't think this warrants the additional complexity, but I'll investigate.

**Comment by pixelzoom** [comment]
> > It would also be good to interrupt the drag listener for the sphere when using the number picker.
> 
> And visa versa, I suspect. In this case, it's complicated to be that selective about what to interrupt -- the manipulators and NumberPickers are in entirely different areas of the code. I don't think this warrants the additional complexity, but I'll investigate.

Much too complicated, and for negligible benefit.  The worst that will happen if a manipulator and NumberPicker are used at the same time is that they will appear to "fight" since they are both changing the same Property.   So this request will be "won't fix".

**Comment by Nancy-Salpepi** [comment]
This is fixed in main. 

One more thing to think about: 
For Game Levels: interrupting the drag listener when pressing the Start Over button. As of now, if I am holding the sphere with one finger and press the Start Over button with another, I exit the level but I am still holding onto an invisible sphere. Once I lift my finger, I hear the release sound.

**Comment by pixelzoom** [comment]
> One more thing to think about:

Good point. Unfortunately, each sim needs to specify what happens when the 'Start Over' button is pressed.   So while I'd bet that other sims have this issue, there's no way to address it for all sims. Each sim needs to specific `startOverButtonOptions` as I've done for  GL/GSI in https://github.com/phetsims/graphing-lines/commit/487bb550e8623f509b37f881ce3a0527f0bc4779. 

@Nancy-Salpepi please verify in main, assign back to me to cherry pick.

**Comment by pixelzoom** [comment]
I went ahead and did all of the cherry picks, including the scenery and scenery-phet commits identified in https://github.com/phetsims/scenery-phet/issues/849#issuecomment-2062593100.

**Comment by Nancy-Salpepi** [comment]
All looks and sounds good in GL 1.4.0-rc.2 and GSI 1.2.0-rc.2.
Closing.
