### ISSUE TITLE
add a checkbox to remove gridlines

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/graphing-lines#43]
Area Builder currently has a checkbox to add/remove gridlines. 
![screen shot 2015-02-11 at 10 23 45 am](https://cloud.githubusercontent.com/assets/7852916/6152163/36aa0310-b1d8-11e4-8e57-0d034323a547.png)

I was thinking about Graphing Lines and thought that could be a nice feature. It is important to think of slope not only in terms of "rise over run" but also the steepness of a line. If the gridlines are invisible, we can have conversations about slope that do not rely on counting units and can speak more generally about steep, not steep, positive, negative, etc.

**Comment by pixelzoom** [comment]
The control for lines currently looks like this:

![screenshot_203](https://cloud.githubusercontent.com/assets/3046552/6152555/56ac5d72-b1db-11e4-8452-fb9c82f6b8a1.png)

So I think it would be a little odd to have a grid control that is very different - uses an icon instead of words, and is "show" instead of "hide".   If we decide to add the proposed feature, then we should make sure that it coexists nicely with the "Hide lines" feature.

**Comment by amanda-phet** [comment]
That makes sense to me.

**Comment by patricialoeblein** [comment]
I also  think being able to discuss slope qualitatively would be helpful. I can’t get logged into github right now, but I wanted to confirm the usefulness. I am not commenting on how it would impact the sim look or feel because I think Amanda and the team will keep on top of that.

Trish Loeblein
Patricia.Loeblein@colorado.edu<mailto:Patricia.Loeblein@colorado.edu>
PhET K12 Specialist http://phet.colorado.edu/
Conifer HS Chemistry teacher conifer-hs.jeffco.k12.co.us/conifer/html/science/ploeblei/
UNC Mines Co-STEM Liaison Specialist   www.unco.edu/nhs/science/MinesUNC_home.html<http://www.unco.edu/nhs/science/MinesUNC_home.html>

**Comment by pixelzoom** [comment]
Hi Trish,

Thanks for the input.  

I noticed that you posted this email into a GitHub comment.  I edited that comment, and removed the contact info (email signature) that you pasted in.  GitHub is public, so I didn’t think you’d appreciate having your email address picked up by a web crawler.

Chris

**Comment by pixelzoom** [comment]
Assigning this to @ariel-phet since he's listed as "lead designer".  This is a new feature request.  We need to decide whether to accept it, and (if so) do the design work.

**Comment by ariel-phet** [comment]
@pixelzoom for the moment, please do as you suggest and just make a checkbox that says "Hide grid" and put it below "Hide lines"

**Comment by pixelzoom** [comment]
For 2 of 3 screens that will have this control (Slope-Intercept, Point-Slope), adding this control will cause the control panel to extend down below the top of the Reset All button.  See screenshot below.  This has i18n ramifications; that entire control panel's width will now be severely limited because (a) the Reset All button will be to the right of it, and (b) we are center-aligning the 2 control panels.

Options:
(1) Reevaluate whether to include this feature.
(2) Live with limited width, since there are few words in the panel.
(3) Find a new location in all screens for the Reset All button.

Imo, (3) is not really an option, so we'll likely opt for (2).  @ariel-phet do you agree? 

![screenshot_586](https://cloud.githubusercontent.com/assets/3046552/9556026/b88ffcfc-4d8e-11e5-916d-5b6c7eb506b3.png)

**Comment by pixelzoom** [comment]
Another option...

(4) If the bottom panel's width exceeds the width of the top panel, then right align the panels and allow the bottom panel to grow to the left.  This will require relatively complicated layout code.

**Comment by pixelzoom** [comment]
Actually (4) won't work, because the top panel's right edge may past the left edge of the Reset All button.

(5) If maintaining center-aligned panels would cause the bottom panel to overlap the "Reset All" button, then use an alternate layout strategy. Center the top panel in the space between the graph and the right edge of the screen. Center the bottom panel in the space between the graph and the Reset All button.

I am not recommending option (5).

**Comment by pixelzoom** [comment]
For 2 of 3 screens that will have this control (Slope-Intercept, Point-Slope), adding this control will cause the control panel to extend down below the top of the Reset All button.  See screenshot below.  This has i18n ramifications; that entire control panel's width will now be severely limited because (a) the Reset All button will be to the right of it, and (b) we are center-aligning the 2 control panels.

Options:
(1) Reevaluate whether to include this feature.
(2) Live with limited width, since there are few words in the panel.
(3) If maintaining center-aligned panels would cause the bottom panel to overlap the "Reset All" button, then use an alternate layout strategy. Center the top panel in the space between the graph and the right edge of the screen. Center the bottom panel in the space between the graph and the Reset All button.

I recommend option (3).

![screenshot_586](https://cloud.githubusercontent.com/assets/3046552/9556026/b88ffcfc-4d8e-11e5-916d-5b6c7eb506b3.png)

**Comment by pixelzoom** [comment]
@ariel-phet Is option (3) is agreeable?

**Comment by pixelzoom** [comment]
I've added the check box, still need to address the i18n layout.  See first screenshot below of what it looks like with "stringTest=double".  So perhaps options (2) is sufficient, which would require no layout changes.

![screenshot_588](https://cloud.githubusercontent.com/assets/3046552/9556759/71a281d8-4d94-11e5-8522-c13679164ee3.png)

**Comment by pixelzoom** [comment]
@ariel-phet One additional question... Are you OK with the vertical spacing after adding the "Hide grid" check box? The spacing is the same between each component is the same.  But some components are taller than others, so the space between the actual rectangular check boxes is different.  The vertical layout (VBox) does not support varying the amount of space between components, so I would need to add a vertical strut if you want the spacing between boxes to be similar.  I'm inclined to leave this as is.

**Comment by amanda-phet** [comment]
You put a lot of thought in to the design choices and I think option (2) looks really good. I know you asked @ariel-phet about the spacing but I will throw it out there that the spacing looks very normal to me. It is typical to expect spacing like that when different rows have different heights.

**Comment by pixelzoom** [comment]
Thanks for reviewing @amanda-phet!  I'm OK with the current look, and how it handles i18n.  @ariel-phet if you're OK with this this too, please close this issue.  Otherwise please specify what additional work you'd like me to do.

Here's a dev version with this feature, if you'd like to test-drive it:

http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.1.0-dev.1/graphing-lines_en.html

**Comment by ariel-phet** [comment]
Looks good to me.Closing
