### ISSUE TITLE
Temporary workaround for GCD change

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/graphing-lines#86]
Since DOT/Util.gcd is changing to always specify a positive number (https://github.com/phetsims/phetcommon/issues/41#issuecomment-374756028) for correctness, I'm applying a workaround to graphing-lines since it relies on the very-tricky sign behavior of the old implementation.

Ideally code can be simplified to use the new gcd function. It's possible that the sim is fine with the change, but snapshot comparisons pulled up this delta (old gcd behavior on the left, new gcd behavior in the middle, color difference on the right):
![graphing-lines-gcd-sign](https://user-images.githubusercontent.com/480878/37684508-d9de8650-2c55-11e8-82f0-80fd6b495f43.png)

**Comment by pixelzoom** [comment]
The usages in `getSimplifiedRise` and `getSimplifiedRun` should definitely use `Util.gcd`, since the sign of the rise (or run) should be preserved when simplified.  As it is now, if the slope is -2/4 or -2/-4, the simplified slope is wrong. E.g.`-2 * Line.gcd( -2, 4 ) = -2 * -2 = 4`.   This hasn't resulted in a problem only because Math.abs is being used to show rise/run values, and the sign is determined separately based on the (unsimplified) slope.   So to start, I'm going to change these 2 occurrences to `Util.gcd`.

**Comment by pixelzoom** [comment]
The `gcd` usage in `getYIntercept` should also be `Util.gcd`.  Again, we want to preserve the sign of the numerator and denominator.

**Comment by pixelzoom** [comment]
I review the snapshot comparisons that @jonathanolson provided (here and in Slack).  The differences are where the negative sign is put in the slope.  E.g. for the screenshot in https://github.com/phetsims/graphing-lines/issues/86#issue-307050716, 1/-3 vs -1/3.  This is not significant, so I'm confident that this sim is fine using Util.gcd.  Especially after inspecting the code, where it's clear that I was assuming that Util.gcd was returning a positive number.

Closing.
